server:
  port: 81

spring:
  application:
    name: harParsor

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/harParsor?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: admin
#    password: admin
#    hikari:
#      maximum-pool-size: 10 #최대 pool 크기
#      minimum-idle: 10 #최소 pool 크기

    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:har2jmx;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # DB_CLOSE_DELAY=-1: 애플리케이션 종료 전까지 DB 유지
#    url: jdbc:h2:file:~/har2jmx;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # DB_CLOSE_DELAY=-1: 애플리케이션 종료 전까지 DB 유지
    username: sa
    password:
  h2:
    console:
      enabled: true         # H2 웹 콘솔 활성화
      path: /h2-console     # 기본 경로: http://localhost:81/h2-console

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true          # SQL 예쁘게 정렬해서 출력
    hibernate:
      ddl-auto: create      # 필요 시 create, create-drop, none, validate 등
#    database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      max-file-size: -1 # 50MB
      max-request-size: -1 # 50MB

  thymeleaf:
    prefix: classpath:/templates/   # Optional
    suffix: .html                   # Optional
    cache: false                    # Optional (default: true)

logging:
  level:
    com.shshin: DEBUG
    org.hibernate: WARN

harParsor:
  queryString:
    type: PARAMETER-TYPE # PATH-PARAMETER-TYPE (url에서 ?이하를 그대로 살림), 그 외 아무글자나.
